<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Oib.Vezba01.Application/Oib.Vezba01.Application.csproj" />
    <ProjectReference Include="../Oib.Vezba01.Infrastructure/Oib.Vezba01.Infrastructure.csproj" />
  </ItemGroup>
</Project>
