<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Oib.Vezba04.Application/Oib.Vezba04.Application.csproj" />
    <ProjectReference Include="../Oib.Vezba04.Infrastructure/Oib.Vezba04.Infrastructure.csproj" />
  </ItemGroup>
</Project>
