<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Oib.Vezba06.Application/Oib.Vezba06.Application.csproj" />
    <ProjectReference Include="../Oib.Vezba06.Infrastructure/Oib.Vezba06.Infrastructure.csproj" />
  </ItemGroup>
</Project>
